name: attendance_interface
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2 # keep your current version
  http: ^1.1.0
  path: ^1.8.2
  image: ^4.2.0
  permission_handler: ^11.3.1


  # Firebase
  firebase_core: ^3.4.0
  firebase_storage: ^12.4.10
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.2.0

  # Image picker
  image_picker: ^1.0.2

  # Icons for iOS-styled apps
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
